version: "3"

services:
  react:
    restart: always
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "3000:3000"
    command: 'npm start'
    volumes:
      - .:/code
      - /code/node_modules